import type { Metadata } from "next";
import { Geist, Geist_Mono, Alumni_Sans_SC, DM_Serif_Text } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

import Provider from "../server/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const alumni = Alumni_Sans_SC({
  subsets: ["latin"],
  variable: "--font-alumni-sans-sc",
  display: "swap",
});

const dmSerifText = DM_Serif_Text({
  subsets: ["latin"],
  variable: "--font-dm-serif-text",
  weight: "400",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${alumni.className} ${geistMono.variable} ${dmSerifText.variable} antialiased bg-black text-white`}
        >
          <Provider>{children}</Provider>

        </body>
      </html>
    </ClerkProvider>
  );
}
